Set-Alias ll Get-ChildItem
Set-Alias la List-DirectoryAll
Set-Alias ld List-DirectoriesOnly
Set-Alias lf List-FilesOnly
Set-Alias ldf List-DotFilesOnly
Set-Alias cc Clear-Host
Set-Alias sls Select-String
Set-Alias off Stop-Computer
Set-Alias pro Reload-Profile
Set-Alias aws "C:\Python34\Scripts\aws.cmd"
Set-Alias nf New-File
Set-Alias nd New-Directory
Set-Alias g git
Set-Alias cod Open-VSCode