Set-Alias ll Get-ChildItem
Set-Alias la Get-ChildItem
Set-Alias cc Clear-Host
Set-Alias sls Select-String
Set-Alias halt Stop-Computer
Set-Alias pro Reload-Profile
Set-Alias aws "C:\Python34\Scripts\aws.cmd"
Set-Alias nf New-File
Set-Alias nd New-Directory